// Downloads the two web fonts into public/fonts and writes src/fonts.css.
//
// Why vendored rather than @import'd from Google: this app has to work with no
// network on first launch. As a packaged app that is a hard requirement — an
// app whose own typeface arrives over the wire has a broken cold start on a
// plane or in a clinic basement. Re-run with `npm run fonts` to refresh.
import { writeFileSync, mkdirSync } from "node:fs";

const URL_ = "https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:wght@400;700&family=Bricolage+Grotesque:wght@600;700&display=swap";
// woff2 needs a modern-browser UA; a bare fetch gets offered woff/ttf instead.
const UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

mkdirSync("src/fonts", { recursive: true });
const css = await (await fetch(URL_, { headers: { "User-Agent": UA } })).text();

// Keep only the `latin` subset. The app is English-only, so latin-ext,
// vietnamese and cyrillic are pure payload.
const blocks = css.split("@font-face").slice(1)
  .map((b) => "@font-face" + b.slice(0, b.indexOf("}") + 1))
  .filter((b) => /U\+0000-00FF/.test(b));

const out = [];
for (const b of blocks) {
  const fam = /font-family: '([^']+)'/.exec(b)[1];
  const wt = /font-weight: (\d+)/.exec(b)[1];
  const url = /url\((https:[^)]+)\)/.exec(b)[1];
  const file = `${fam.toLowerCase().replace(/\s+/g, "-")}-${wt}.woff2`;
  const buf = Buffer.from(await (await fetch(url)).arrayBuffer());
  writeFileSync(`src/fonts/${file}`, buf);
  console.log(`  ${file}  ${(buf.length / 1024).toFixed(1)} KB`);
  out.push(
    `@font-face {\n  font-family: '${fam}';\n  font-style: normal;\n  font-weight: ${wt};\n` +
    `  font-display: swap;\n  src: url('./fonts/${file}') format('woff2');\n}`
  );
}

writeFileSync("src/fonts.css",
  "/* GENERATED by scripts/fetch-fonts.mjs — do not hand-edit. */\n" + out.join("\n") + "\n");
console.log(`\nWrote src/fonts.css (${out.length} faces)`);
