#!/usr/bin/env node
// Tag every sentence in the app with its §6 ladder data: target word, the
// target's sound category, and how many instances of that sound the sentence
// carries (function words never count). 1 instance → set 1, 2 → set 2,
// 3+ → set 3. Stored in the data file (src/sentences.gen.js), not computed at
// runtime, so the ladder can be recomposed later (§6A user-adjustable
// difficulty). Appends a bucket-inventory audit to vocab-audit.md.
//   node scripts/tag_sentences.mjs   (run AFTER build_words.py)
import { writeFileSync, appendFileSync, readFileSync } from "fs";
import { utilityScore } from "./utility_score.mjs";

const { SENTENCES, SCENARIO_SENTENCES, SCENARIOS, FUNCTIONAL, topTarget, ladderTarget, catOf, sentenceInstances, syllables, cleanToken } =
  await import("../src/data.js");

// §7 pacing input: a sentence's syllable count, using the same vowel-group rule
// build_words.py applies to the word pool, so words and sentences are measured
// on one scale. The drill words average 2.6 syllables and sentence words 1.38 —
// pacing a sentence by word count alone is what made short, monosyllabic lines
// drag (CB 2026-08-19).
const sentSyllables = (s) =>
  s.split(/\s+/).reduce((a, t) => a + syllables(cleanToken(t)), 0);

const meta = {};
const tag = (s) => {
  const y = sentSyllables(s);
  const p = utilityScore(s);
  const w = ladderTarget(s);
  if (!w) { meta[s] = { w: topTarget(s), cat: null, n: 0, y, p }; return; }
  const cat = catOf(w);
  meta[s] = { w, cat, n: sentenceInstances(s, cat), y, p };
};
Object.values(SENTENCES).flat().forEach(tag);
Object.values(SCENARIO_SENTENCES).flat().forEach(tag);
FUNCTIONAL.forEach(tag);

let js = "// GENERATED by scripts/tag_sentences.mjs — do not edit by hand.\n";
js += "// { w: target word, cat: its sound category, n: instances of that sound,\n";
js += "//   y: syllables in the whole sentence, p: daily-use probability 1-5 }\n";
js += "// n drives the §6 ladder: 1 → set 1, 2 → set 2, 3+ → set 3.\n";
js += "// y drives §7 pacing — a sentence is held for its syllables, not its words.\n";
js += "// p weights selection — see scripts/utility_score.mjs.\n";
js += "export const SENT_META = " + JSON.stringify(meta) + ";\n";
writeFileSync("src/sentences.gen.js", js);

// --- audit: can each bank fill a 10-couple set per ladder rung? ------------
const bucket = (list) => {
  const b = { 1: 0, 2: 0, 3: 0, none: 0 };
  for (const s of list) {
    const { n, cat } = meta[s];
    if (!cat || n === 0) b.none++;
    else if (n === 1) b[1]++;
    else if (n === 2) b[2]++;
    else b[3]++;
  }
  return b;
};
const rows = [];
const scenName = Object.fromEntries(SCENARIOS.map((s) => [s.id, s.name]));
const practiceBank = [...Object.values(SCENARIO_SENTENCES).flat(), ...Object.values(SENTENCES).flat()];
rows.push(["Practice (all banks)", practiceBank]);
for (const [id, list] of Object.entries(SCENARIO_SENTENCES)) rows.push([scenName[id] || id, list]);

// Rewrite the section instead of appending — re-running the tagger used to
// stack a fresh copy of this table on the end of the audit every time.
const AUDIT_H = "## Sentence ladder inventory (§6) — instances of the target sound per sentence";
const prior = readFileSync("vocab-audit.md", "utf8");
const cut = prior.indexOf("\n" + AUDIT_H);
if (cut >= 0) writeFileSync("vocab-audit.md", prior.slice(0, cut).replace(/\s+$/, "") + "\n");

let audit = "\n" + AUDIT_H + "\n\n";
audit += "A couples set needs 10 sentences. Set 1 uses exactly-1-instance sentences, set 2 exactly 2, set 3 uses 3+. ";
audit += "Where a rung has fewer than 10, the app falls back to the nearest rung rather than inventing sentences — flagged below.\n\n";
audit += "| Bank | 1 instance (set 1) | 2 instances (set 2) | 3+ (set 3) | no target sound | flags |\n|---|---|---|---|---|---|\n";
const flagged = [];
for (const [name, list] of rows) {
  const b = bucket(list);
  const flags = [];
  for (const rung of [1, 2, 3]) if (b[rung] < 10) flags.push(`set ${rung} rung thin (${b[rung]})`);
  if (flags.length) flagged.push(name);
  audit += `| ${name} | ${b[1]} | ${b[2]} | ${b[3]} | ${b.none} | ${flags.join("; ")} |\n`;
}
// --- audit: does sound density trade against real-world usefulness? --------
// The number that matters is the last column: at rung 3 it was 2% before the
// high-use rewrite. If it drops again, dense sentences are being written to
// hit a sound target instead of to be spoken.
audit += "\n## Daily-use probability (`p`) against ladder rung — scenario banks\n\n";
audit += "`p` is 1-5, scored by `scripts/utility_score.mjs`. \"Says I/my/we\" and \"is a request or question\" are raw structural counts, no judgment involved.\n\n";
audit += "| Rung | Sentences | Mean p | Says I/my/we | Is a request or question |\n|---|---|---|---|---|\n";
const scenAll = Object.values(SCENARIO_SENTENCES).flat();
const speaks = (s) => /\b(i|i'd|i'll|i'm|i've|me|my|we|we're|we'd|our|us)\b/i.test(s);
const asks = (s) => /\?\s*$/.test(s.trim()) || /^(can|could|may|would|will)\s+(i|we|you)\b|^(i'd like|i would like|i need|i'll have|i'll take|i want)\b|,\s*please\.?$/i.test(s.trim());
for (const r of [1, 2, 3]) {
  const g = scenAll.filter((s) => { const m = meta[s]; return m.cat && Math.min(m.n, 3) === r; });
  if (!g.length) continue;
  const pct = (f) => Math.round((100 * g.filter(f).length) / g.length) + "%";
  audit += `| ${r} | ${g.length} | ${(g.reduce((a, s) => a + meta[s].p, 0) / g.length).toFixed(2)} | ${pct(speaks)} | ${pct(asks)} |\n`;
}
appendFileSync("vocab-audit.md", audit);
console.log(`tagged ${Object.keys(meta).length} sentences -> src/sentences.gen.js`);
for (const [name, list] of rows) console.log(name, bucket(list));
if (flagged.length) console.log("THIN RUNGS:", flagged.join(", "));
